(ql:quickload 'cl-ncurses)

(defpackage slider
  (:use #:cl-ncurses #:cl #:cl-user #:uffi))

(in-package slider)

(defmacro with-cs (s &body body)
  `(let ,(mapcar (lambda (s)
                   (if (and (consp s)
                            (= 2 (length s)))
                     `(,(car s) (convert-to-cstring ,(cadr s)))
                     (error "with-cs: wrong pattern")))
                 s)
     ,@body
     ,@(mapcar (lambda (s) `(free-cstring ,(car s))) s)))

(defun init-mainwindow ()
  (initscr)
  (raw)
  (noecho)
  (curs-set 0)
  (init-color-ncurses)
  (clear)
  (refresh))

(defstruct as
  reverse bold underline)
(defparameter as-current (make-as :reverse nil
                                  :bold nil
                                  :underline nil))
(defparameter as-stack '())

(defun set-as (as lst)
  (dolist (i lst)
    (case i
      (reverse (setf (as-reverse as) t))
      (bold (setf (as-bold as) t))
      (underline (setf (as-underline as) t)))))

(defun copy-as (old)
  (let ((new (make-as)))
    (setf (as-reverse new) (as-reverse old))
    (setf (as-bold new) (as-bold old))
    (setf (as-underline new) (as-underline old))
    new))

(defun apply-as (as)
  (if (as-reverse as) (attron a_reverse))
  (if (as-bold as) (attron a_bold))
  (if (as-underline as) (attron a_underline)))

(defun cancel-as (as)
  (if (as-reverse as) (attroff a_reverse))
  (if (as-bold as) (attroff a_bold))
  (if (as-underline as) (attroff a_underline)))

(defmacro with-attr (attrs &body body)
  (let ((newas (gensym)))
    `(progn (push (copy-as as-current) as-stack)
            (let ((,newas (make-as)))
              (set-as ,newas (quote ,attrs))
              (setf as-current ,newas)
              (apply-as as-current)
              ,@body
              (cancel-as as-current)
              (setf as-current (pop as-stack))
              (apply-as as-current)))))

(defparameter *color-table* (make-hash-table))
(defun set-color-table (color-list)
  (dolist (i color-list)
    (let ((color (car i))
          (c (cdr i)))
      (setf (gethash color *color-table*) c))))
(set-color-table '((black . color_black)
                   (red . color_red)
                   (green . color_green)
                   (yellow . color_yellow)
                   (blue . color_blue)
                   (magenta . color_magenta)
                   (cyan . color_cyan)
                   (white . color_white)))
(defun get-color (c) (gethash c *color-table*))

(defun init-color-ncurses ()
  (start-color)
  (init-pair COLOR_BLACK   COLOR_BLACK   COLOR_BLACK)
  (init-pair COLOR_GREEN   COLOR_GREEN   COLOR_BLACK)
  (init-pair COLOR_RED     COLOR_RED     COLOR_BLACK)
  (init-pair COLOR_CYAN    COLOR_CYAN    COLOR_BLACK)
  (init-pair COLOR_WHITE   COLOR_WHITE   COLOR_BLACK)
  (init-pair COLOR_MAGENTA COLOR_MAGENTA COLOR_BLACK)
  (init-pair COLOR_BLUE    COLOR_BLUE    COLOR_BLACK)
  (init-pair COLOR_YELLOW  COLOR_YELLOW  COLOR_BLACK))

(defun set-background (color)
  (let ((bg (eval (get-color color))))
    (init-pair COLOR_BLACK   COLOR_BLACK   bg)
    (init-pair COLOR_GREEN   COLOR_GREEN   bg)
    (init-pair COLOR_RED     COLOR_RED     bg)
    (init-pair COLOR_CYAN    COLOR_CYAN    bg)
    (init-pair COLOR_WHITE   COLOR_WHITE   bg)
    (init-pair COLOR_MAGENTA COLOR_MAGENTA bg)
    (init-pair COLOR_BLUE    COLOR_BLUE    bg)
    (init-pair COLOR_YELLOW  COLOR_YELLOW  bg)
    (init-pair 80 color_black bg)
    (bkgd (color-pair 80))))

(defparameter color-stack '())
(defparameter color-current 0)

(defmacro with-color (color &body body)
  `(progn (push color-current color-stack)
          (setf color-current ,(get-color color))
          (attron (color-pair color-current))
          ,@body
          (attroff (color-pair color-current))
          (setf color-current (pop color-stack))
          (attron (color-pair color-current))))

(defun draw-bottom-panel ()
  (let ((help "help"))
    (with-cs ((c_help help)
              (c_space " "))
      (with-color black
        (with-attr (reverse bold)
          (dotimes (x *cols*)
            (mvprintw (1- *lines*) x c_space))
          (mvprintw (1- *lines*)
                    (- *cols* (length help))
                    c_help))))))

(defun gen-render-code (render-exp)
  (if (consp render-exp)
    (case (car render-exp)
      (body `(progn ,@(mapcar #'gen-render-code (cdr render-exp))))
      (reverse (macroexpand
                 `(with-attr (reverse)
                    ,@(mapcar #'gen-render-code (cdr render-exp)))))
      (bold (macroexpand
              `(with-attr (bold)
                 ,@(mapcar #'gen-render-code (cdr render-exp)))))
      (underline (macroexpand
                   `(with-attr (underline)
                      ,@(mapcar #'gen-render-code (cdr render-exp)))))
      (br '(wprintw *stdscr* (format nil "~%")))
      (color (macroexpand
               `(with-color ,(let ((c (cadr render-exp)))
                               (if (get-color c)
                                 c 'black))
                  ,@(mapcar #'gen-render-code (cddr render-exp)))))
      (lisp (cadr render-exp))
      (t (format t "gen-render-code: warning!! illegal tag: ~A~%"
                 (car render-exp))))
    (if (stringp render-exp)
      (let ((token (gensym)))
        (macroexpand `(with-cs ((,token ,render-exp))
                        (wprintw *stdscr* ,token))))
      (let ((str (format nil "*~A*" render-exp))
            (token (gensym)))
        (macroexpand `(with-cs ((,token ,str))
                        (wprintw *stdscr* ,token)))))))
